apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: my-{{ .Values.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: {{ .Values.name }}
  template:
    metadata:
      labels:
        project: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}