apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    env: prod
spec:
  selector:
    project: {{ .Values.name }}
  ports:
   - port: {{ .Values.container.port }}
     targetPort: {{ .Values.container.port }}
  type: LoadBalancer
 